import { NextResponse } from "next/server"

const destinations = [
  {
    id: 1,
    name: "Paris",
    country: "France",
    image: "/images/shutterstock_2464630783-scaled.jpg",
    description: "The City of Lights, known for its art, fashion, and the Eiffel Tower.",
    rating: 4.8,
    reviews: 1240,
    bestTimeToVisit: "April–June, September–October",
    activities: ["Sightseeing", "Museums", "Cafes", "River Cruise"],
    priceLevel: "$$$",
    continent: "Europe"
  },
  {
    id: 2,
    name: "Bali",
    country: "Indonesia",
    image: "/images/bali-for-digital-nomads.jpg",
    description: "A tropical paradise with beaches, rice terraces, and vibrant culture.",
    rating: 4.7,
    reviews: 980,
    bestTimeToVisit: "April–October",
    activities: ["Surfing", "Yoga Retreats", "Temples", "Beaches"],
    priceLevel: "$$",
    continent: "Asia"
  },
  {
    id: 3,
    name: "New York",
    country: "USA",
    image: "/images/caption.jpg",
    description: "The city that never sleeps, full of iconic landmarks and culture.",
    rating: 4.6,
    reviews: 1500,
    bestTimeToVisit: "April–June, September–November",
    activities: ["Broadway", "Museums", "Shopping", "Sightseeing"],
    priceLevel: "$$$",
    continent: "North America"
  },
  {
    id: 4,
    name: "Tokyo",
    country: "Japan",
    image: "/images/tokyo-for-digital-nomads.jpg",
    description: "A bustling metropolis combining modernity with traditional culture.",
    rating: 4.7,
    reviews: 1120,
    bestTimeToVisit: "March–May, October–November",
    activities: ["Shopping", "Temples", "Anime Culture", "Food Tours"],
    priceLevel: "$$$",
    continent: "Asia"
  },
  {
    id: 5,
    name: "Rome",
    country: "Italy",
    image: "/images/rome.jpg",
    description: "Ancient city with rich history, art, and architecture.",
    rating: 4.8,
    reviews: 950,
    bestTimeToVisit: "April–June, September–October",
    activities: ["Historical Tours", "Museums", "Cuisine", "Churches"],
    priceLevel: "$$$",
    continent: "Europe"
  },
  {
    id: 6,
    name: "Barcelona",
    country: "Spain",
    image: "/images/spain.jpg",
    description: "Famous for Gaudí’s architecture, beaches, and vibrant nightlife.",
    rating: 4.7,
    reviews: 870,
    bestTimeToVisit: "May–June, September–October",
    activities: ["Architecture", "Beaches", "Museums", "Nightlife"],
    priceLevel: "$$",
    continent: "Europe"
  },
  {
    id: 7,
    name: "London",
    country: "UK",
    image: "/images/london.jpg",
    description: "Historic city with iconic landmarks like Big Ben and the London Eye.",
    rating: 4.6,
    reviews: 1400,
    bestTimeToVisit: "April–June, September–October",
    activities: ["Museums", "Sightseeing", "Theatre", "Shopping"],
    priceLevel: "$$$",
    continent: "Europe"
  },
  {
    id: 8,
    name: "Dubai",
    country: "UAE",
    image: "/images/dubai.jpg",
    description: "Luxury destination with skyscrapers, desert adventures, and shopping.",
    rating: 4.5,
    reviews: 980,
    bestTimeToVisit: "November–March",
    activities: ["Desert Safari", "Shopping", "Beach", "Sightseeing"],
    priceLevel: "$$$",
    continent: "Asia"
  },
  {
    id: 9,
    name: "Singapore",
    country: "Singapore",
    image: "/images/singapore.jpg",
    description: "Modern city-state known for gardens, food, and skyline.",
    rating: 4.6,
    reviews: 850,
    bestTimeToVisit: "February–April, July–October",
    activities: ["Gardens", "Food Tours", "Museums", "Shopping"],
    priceLevel: "$$$",
    continent: "Asia"
  },
  {
    id: 10,
    name: "Sydney",
    country: "Australia",
    image: "/images/sydney.jpg",
    description: "Home to the Opera House, beaches, and a vibrant lifestyle.",
    rating: 4.7,
    reviews: 910,
    bestTimeToVisit: "September–November, March–May",
    activities: ["Beaches", "Sightseeing", "Harbour Cruise", "Nature"],
    priceLevel: "$$$",
    continent: "Oceania"
  },
  {
    id: 11,
    name: "Bangkok",
    country: "Thailand",
    image: "/images/bangkok.jpg",
    description: "Bustling capital city with temples, street food, and markets.",
    rating: 4.5,
    reviews: 890,
    bestTimeToVisit: "November–February",
    activities: ["Temples", "Markets", "Food Tours", "Nightlife"],
    priceLevel: "$$",
    continent: "Asia"
  },
  {
    id: 12,
    name: "Istanbul",
    country: "Turkey",
    image: "/images/istanbul.jpg",
    description: "City where East meets West, rich in history and culture.",
    rating: 4.6,
    reviews: 780,
    bestTimeToVisit: "April–May, September–October",
    activities: ["Historical Sites", "Bazaars", "Cultural Tours", "Museums"],
    priceLevel: "$$",
    continent: "Europe"
  },
  {
    id: 13,
    name: "Seoul",
    country: "South Korea",
    image: "/images/seoul.jpg",
    description: "Vibrant capital known for tech, pop culture, and historic palaces.",
    rating: 4.7,
    reviews: 720,
    bestTimeToVisit: "March–May, September–November",
    activities: ["Palaces", "Food Tours", "Shopping", "K-Pop Experiences"],
    priceLevel: "$$",
    continent: "Asia"
  },
  {
    id: 14,
    name: "Los Angeles",
    country: "USA",
    image: "/images/la.jpg",
    description: "City of angels with beaches, Hollywood, and cultural hotspots.",
    rating: 4.6,
    reviews: 980,
    bestTimeToVisit: "March–May, September–November",
    activities: ["Beaches", "Hollywood Tours", "Shopping", "Sightseeing"],
    priceLevel: "$$$",
    continent: "North America"
  },
  {
    id: 15,
    name: "Chicago",
    country: "USA",
    image: "/images/chicago.jpg",
    description: "Known for its skyline, architecture, and deep-dish pizza.",
    rating: 4.5,
    reviews: 850,
    bestTimeToVisit: "May–September",
    activities: ["Architecture Tours", "Museums", "Food Tours", "Lakefront"],
    priceLevel: "$$",
    continent: "North America"
  },
  {
    id: 16,
    name: "Cape Town",
    country: "South Africa",
    image: "/images/capetown.jpg",
    description: "Coastal city with mountains, beaches, and wildlife.",
    rating: 4.7,
    reviews: 740,
    bestTimeToVisit: "November–March",
    activities: ["Table Mountain", "Beaches", "Wine Tours", "Safari"],
    priceLevel: "$$",
    continent: "Africa"
  },
  {
    id: 17,
    name: "Rio de Janeiro",
    country: "Brazil",
    image: "/images/rio.jpg",
    description: "Famous for beaches, Carnival, and the Christ the Redeemer statue.",
    rating: 4.6,
    reviews: 780,
    bestTimeToVisit: "December–March",
    activities: ["Beaches", "Carnival", "Sightseeing", "Hiking"],
    priceLevel: "$$",
    continent: "South America"
  },
  {
    id: 18,
    name: "Amsterdam",
    country: "Netherlands",
    image: "/images/amsterdam.jpg",
    description: "Canal city with museums, bikes, and charming architecture.",
    rating: 4.7,
    reviews: 720,
    bestTimeToVisit: "April–June, September–October",
    activities: ["Canal Tours", "Museums", "Biking", "Cafes"],
    priceLevel: "$$",
    continent: "Europe"
  },
  {
    id: 19,
    name: "Prague",
    country: "Czech Republic",
    image: "/images/prague.jpg",
    description: "Historic city with castles, cobblestone streets, and culture.",
    rating: 4.8,
    reviews: 680,
    bestTimeToVisit: "May–September",
    activities: ["Castle Tours", "Historic Districts", "Museums", "Food"],
    priceLevel: "$$",
    continent: "Europe"
  },
  {
    id: 20,
    name: "Vienna",
    country: "Austria",
    image: "/images/vienna.jpg",
    description: "Elegant city famous for music, art, and coffee culture.",
    rating: 4.7,
    reviews: 650,
    bestTimeToVisit: "April–June, September–October",
    activities: ["Palaces", "Museums", "Music Concerts", "Cafes"],
    priceLevel: "$$",
    continent: "Europe"
  }
]

export async function GET() {
  return NextResponse.json(destinations)
}